### ISSUE TITLE
[BUG] Create /home/jenkins on startup

### ISSUE THREAD

**Issue by madmath03** [bitnami/bitnami-docker-jenkins#56] opened 2020-02-14 22:27 UTC
**Description**

**Steps to reproduce the issue:**

1. Setup a Jenkins job that uses maven (could be a freestyle, maven or pipeline)
2. Run the job directly on Jenkins (no external slave or docker container)

**Describe the results you received:**

By default maven will use the jenkins user home directory `/home/jenkins/`, not the Jenkins Server home, resulting in an error:
```
ERROR: Failed to create /home/jenkins/.m2
```

**Describe the results you expected:**

`/home/jenkins/` exists and is owned by `jenkins` user.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

Jenkins: 2.204.2

- Output of `docker version`:

```
Docker version 18.09.9, build 039a7df9ba
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Comment by marcosbc** [comment] 2020-02-17 12:00
Hi, just wanted to let you know that we reproduced the issue and are looking into this.

**Comment by carrodher** [comment] 2020-02-18 08:16
I just added the `on-hold` label to prevent `stale-bot` closing this issue if there are no new comments in the following days.

**Comment by marcosbc** [comment] 2020-02-28 14:20
Hi @madmath03, we released a new version of the Bitnami Jenkins Docker image, with the tag ` 2.204.2-debian-10-r27` and it includes the fix for this issue.

Basically we fixed the home directory for the Jenkins user to be `/opt/bitnami/jenkins/jenkins_home`. Let us know if you find any issues with this.

**Comment by juan131** [comment] 2021-06-03 09:16
Closing due to lack of activity. Reopen it if you require further help.

**Closed by juan131** 2021-06-03 09:16 UTC
Labels: on-hold
